import { mkdir, rename, rm } from "node:fs/promises";
import { extname, resolve } from "node:path";

const rootDir = resolve(import.meta.dir, "..");
const entrypoint = resolve(rootDir, "src/web/main.tsx");
const buildDir = resolve(rootDir, `.tmp/web-build-${process.pid}`);
const generatedDir = resolve(rootDir, ".generated");
const generatedPath = resolve(generatedDir, "web-assets.ts");
const replacementPath = resolve(generatedDir, `.web-assets.ts.${process.pid}.tmp`);

await rm(buildDir, { recursive: true, force: true });
await mkdir(buildDir, { recursive: true });

try {
  const result = await Bun.build({
    entrypoints: [entrypoint],
    outdir: buildDir,
    target: "browser",
    splitting: false,
    minify: true,
    sourcemap: "none",
    naming: {
      entry: "app.[ext]",
      asset: "[name].[ext]",
    },
  });

  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error("Browser build failed");
  }

  const javascriptOutputs = result.outputs.filter((output) => extname(output.path) === ".js");
  const cssOutputs = result.outputs.filter((output) => extname(output.path) === ".css");

  if (javascriptOutputs.length !== 1 || cssOutputs.length !== 1 || result.outputs.length !== 2) {
    throw new Error(
      `Expected exactly one JavaScript and one CSS output, received ${javascriptOutputs.length} JavaScript, ${cssOutputs.length} CSS, and ${result.outputs.length} total`,
    );
  }

  const [javascript, css] = await Promise.all([
    javascriptOutputs[0]!.text(),
    cssOutputs[0]!.text(),
  ]);

  if (javascript.length === 0 || css.length === 0) {
    throw new Error("Browser build produced an empty JavaScript or CSS artifact");
  }

  const generated = [
    "// Generated by scripts/build-web.ts. Do not edit.",
    `export const webJavaScript = ${JSON.stringify(javascript)};`,
    `export const webStylesheet = ${JSON.stringify(css)};`,
    "",
  ].join("\n");

  await mkdir(generatedDir, { recursive: true });
  await Bun.write(replacementPath, generated);
  await rename(replacementPath, generatedPath);

  console.log(`Generated ${generatedPath} (${javascript.length} bytes JS, ${css.length} bytes CSS)`);
} finally {
  await rm(buildDir, { recursive: true, force: true });
  await rm(replacementPath, { force: true });
}
